server:
  port: 8080

database:
  driver: mysql
  host: localhost
  port: 3306
  username: 'root'
  password: '111111'
  dbname: users

redis:
  host: localhost
  port: 6379
  password: '111111'
  db: 0

jwt:
  secret: 'wS8hS8dJ1nG2dV3qS6yH1jA5xV7zF7fN'
  expire-time: 24

white_list:
  - '/api/v1/login'
  - '/api/v1/register'

api_permits:
  - method: 'POST'
    path: '/api/v1/users/list'
    permits: 'user:list'

  - method: 'POST'
    path: '/api/v1/users/get'
    permits: 'user:get'

  - method: 'POST'
    path: '/api/v1/users/update'
    permits: 'user:update'

  - method: 'POST'
    path: '/api/v1/users/delete'
    permits: 'user:delete'


logger:
  level: info
